# Generated by Django 4.0.8 on 2023-10-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_created_on_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=100, max_length=200),
        ),
    ]
